<!-- generated by GPT-5.2 -->
<script>
  import { generateCppTeachingTrace } from './cpp-memory/engine';

  let {
    code = `int x = 3;
int y;
y = x + 2;`,
    title = 'C++ Memory Stepper',
    showWrapper = true,
    wrapperSignature = 'int main()',
  } = $props();

  let showDeallocated = $state(false);
  const traceOutput = $derived(generateCppTeachingTrace(code));

  const result = $derived(traceOutput.ok ? traceOutput : null);
  const errorMessage = $derived(!traceOutput.ok ? traceOutput.message : null);
  const errorHint = $derived(!traceOutput.ok ? traceOutput.hint : null);

  const steps = $derived(result?.steps ?? []);
  const lines = $derived(
    result?.lines ?? code.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n')
  );

  let stepIndex = $state(0);

  function formatCodeLines(rawLines, baseIndentLevel = 0) {
    let indentLevel = baseIndentLevel;
    return rawLines.map((raw) => {
      const line = String(raw).replace(/\t/g, '  ').replace(/\s+$/g, '');
      const trimmed = line.trim();
      if (trimmed.length === 0) return '';

      if (trimmed.startsWith('}')) indentLevel = Math.max(0, indentLevel - 1);
      const formatted = ' '.repeat(indentLevel * 2) + trimmed;
      if (trimmed.endsWith('{')) indentLevel += 1;
      return formatted;
    });
  }

  const displayLines = $derived.by(() => {
    const baseIndent = showWrapper ? 1 : 0;
    const formatted = formatCodeLines(lines, baseIndent);
    if (!showWrapper) return formatted;
    return [`${wrapperSignature} {`, ...formatted, '}'];
  });

  const activeDisplayLineIndex = $derived.by(() => {
    const baseLineIndex = steps[stepIndex]?.lineIndex;
    if (baseLineIndex === undefined) return -1;
    const displayIndex = showWrapper ? baseLineIndex + 1 : baseLineIndex;
    const maxIndex = displayLines.length - 1;
    if (maxIndex < 0) return -1;
    if (displayIndex < 0) return -1;
    if (displayIndex > maxIndex) return maxIndex;
    return displayIndex;
  });

  $effect(() => {
    // Reset when code changes
    if (steps.length === 0) {
      stepIndex = 0;
      return;
    }
    if (stepIndex < 0) stepIndex = 0;
    if (stepIndex >= steps.length) stepIndex = steps.length - 1;
  });

  const currentStep = $derived(stepIndex >= 0 ? steps[stepIndex] : null);

  const currentVars = $derived.by(() => {
    if (!currentStep) return [];
    const vars = currentStep.state.vars;
    return showDeallocated ? vars : vars.filter((v) => v.alive);
  });

  function goPrev() {
    if (stepIndex > 0) stepIndex -= 1;
  }

  function goNext() {
    if (stepIndex >= 0 && stepIndex < steps.length - 1) stepIndex += 1;
  }

  function fmtAddr(n) {
    return '0x' + n.toString(16).toUpperCase().padStart(4, '0');
  }

  function fmtValue(v) {
    if (!v.alive) return '(deallocated)';
    if (v.kind === 'ref') return v.refTarget ? `alias @ ${fmtAddr(v.address)}` : '(dangling ref)';
    if (v.value === null) return '??';
    return String(v.value);
  }
</script>

<div>
  <div class="hidden print:block text-sm italic text-slate-600">
    Interactive memory stepper example is not available when printing. Please view this page online.
  </div>

  <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm print:hidden dark:border-slate-800 dark:bg-slate-950">
  <div class="mb-3 flex flex-wrap items-center justify-between gap-2">
    <h3 class="m-0 text-base font-semibold text-slate-900 dark:text-slate-100">{title}</h3>

    {#if result}
      <div class="mt-0 text-xs text-slate-600 dark:text-slate-300">
        Model: int={result.config.intSize}B, double={result.config.doubleSize}B, bool={result.config.boolSize}B,
        char={result.config.charSize}B, eval={result.config.evaluationOrder}
      </div>
    {/if}
  </div>

  {#if errorMessage}
    <div class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-900 dark:border-red-900/50 dark:bg-red-950/40 dark:text-red-100">
      <div class="font-semibold">Trace error</div>
      <div class="mt-1">{errorMessage}</div>
      {#if errorHint}
        <div class="mt-2 text-xs opacity-90">{errorHint}</div>
      {/if}
    </div>
  {:else}
    <div class="flex flex-col gap-4">
      <div class="min-w-0">
        <div class="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
          Code
        </div>
        <div class="overflow-auto rounded-lg border border-slate-200 bg-slate-50 font-mono text-sm dark:border-slate-800 dark:bg-slate-900">
          {#each displayLines as line, i}
            <div
              class={
                'mt-0 flex gap-3 px-3 py-0 leading-5 ' +
                (activeDisplayLineIndex === i
                  ? 'bg-amber-100 text-slate-900 dark:bg-amber-900/30 dark:text-slate-100'
                  : 'text-slate-700 dark:text-slate-200')
              }
            >
              <div class="w-10 select-none text-right text-slate-400 dark:text-slate-500">{i + 1}</div>
              <div class="mt-0 min-w-0 flex-1 whitespace-pre">{line}</div>
            </div>
          {/each}
        </div>

        <div class="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-800 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200">
          <div class="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Step
          </div>
          {#if currentStep}
            <div class="mt-1">
              <div class="font-mono text-xs text-slate-500 dark:text-slate-400">#{stepIndex + 1} / {steps.length}</div>
              <div class="mt-1">{currentStep.explanation}</div>
            </div>
          {:else}
            <div class="mt-1 text-slate-600 dark:text-slate-300">No steps to display.</div>
          {/if}
        </div>

        <div class="mt-3 flex flex-wrap items-center gap-2">
          <button
            type="button"
            class="mt-0 rounded-md border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-900 shadow-sm disabled:opacity-50 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-100"
            onclick={goPrev}
            disabled={stepIndex <= 0}
          >
            Prev
          </button>
          <button
            type="button"
            class="mt-0 rounded-md border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-900 shadow-sm disabled:opacity-50 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-100"
            onclick={goNext}
            disabled={stepIndex < 0 || stepIndex >= steps.length - 1}
          >
            Next
          </button>

          <div class="mt-0 flex-1 min-w-[200px]">
            <input
              type="range"
              min="0"
              max={Math.max(0, steps.length - 1)}
              value={Math.max(0, stepIndex)}
              class="w-full"
              oninput={(e) => {
                const v = Number(e.currentTarget.value);
                stepIndex = v;
              }}
              disabled={steps.length === 0}
            />
          </div>

          <label class="mt-0 flex items-center gap-2 text-sm text-slate-700 dark:text-slate-200">
            <input type="checkbox" bind:checked={showDeallocated} />
            Show deallocated
          </label>
        </div>
      </div>

      <div class="min-w-0">
        <div class="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
          Stack (teaching model)
        </div>
        <div class="overflow-auto rounded-lg border border-slate-200 dark:border-slate-800">
          <table class="w-full border-collapse text-sm">
            <thead class="bg-slate-50 text-left text-xs text-slate-600 dark:bg-slate-900 dark:text-slate-300">
              <tr>
                <th class="px-3 py-2">Name</th>
                <th class="px-3 py-2">Kind</th>
                <th class="px-3 py-2">Type</th>
                <th class="px-3 py-2">Address</th>
                <th class="px-3 py-2">Value</th>
                <th class="px-3 py-2">Scope</th>
                <th class="px-3 py-2">Alive</th>
              </tr>
            </thead>
            <tbody>
              {#each currentVars as v (v.id)}
                <tr
                  class={
                    'border-t border-slate-200 dark:border-slate-800 ' +
                    (v.alive
                      ? 'bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-100'
                      : 'bg-slate-50 text-slate-500 dark:bg-slate-900 dark:text-slate-400')
                  }
                >
                  <td class="px-3 py-2 font-mono">{v.name}</td>
                  <td class="px-3 py-2">{v.kind}</td>
                  <td class="px-3 py-2 font-mono">{v.type}</td>
                  <td class="px-3 py-2 font-mono">{fmtAddr(v.address)}</td>
                  <td class="px-3 py-2 font-mono">{fmtValue(v)}</td>
                  <td class="px-3 py-2">{v.scopeDepth}</td>
                  <td class="px-3 py-2">{v.alive ? 'yes' : 'no'}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>

        <div class="mt-3 text-xs text-slate-600 dark:text-slate-300">
          Notes: References are modeled as aliases (no extra storage). Uninitialized values show as <span class="font-mono">??</span>.
        </div>
      </div>
    </div>
  {/if}
  </div>
</div>
